version: "3.8"

services:
  # Traefik service for reverse proxy
  traefik:
    image: traefik:v2.6
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=true"  # Optional: Exposes Traefik dashboard
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesResolvers.le.acme.httpChallenge.entryPoint=web"
      - "--certificatesResolvers.le.acme.email=youremail@example.com"  # Set your email
      - "--certificatesResolvers.le.acme.storage=/letsencrypt/acme.json"  # Persistent storage
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  # Allows Traefik to listen to Docker events
      - "./letsencrypt:/letsencrypt"  # Persistent storage for SSL certificates

  # Streamlit app service
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit-app
    restart: always
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.streamlit.rule=Host(`yourdomain.com`)"
      - "traefik.http.routers.streamlit.entrypoints=websecure"
      - "traefik.http.routers.streamlit.tls=true"
      - "traefik.http.routers.streamlit.tls.certresolver=le"  # Uses Let's Encrypt

    volumes:
      - .:/app